# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Neeraj Nagar
title: Software Engineer
email: nnagar@uwaterloo.ca
# email_title: Email (Email title override)
phone: (+1)437-808-2696
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false  

# Social links
twitter_username: #jekyllrb
github_username:  neerajnagar26
stackoverflow_username: #"00000001"
dribbble_username: #jekyll
facebook_username: #jekyll
flickr_username: #jekyll
instagram_username: neeraj_nagar26
linkedin_username: neerajnagar26
xing_username: #jekyll
pinterest_username: #jekyll
youtube_username: #jekyll
orcid_username: #0000-0000-0000-0000
googlescholar_username: #D847cGsAAAAJ
leetcode_username: neerajnagar


# Additional icon links
#additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/neeraj_main.jpg
about_content: | # this will include new lines to allow paragraphs

 I am a Graduate Research Student at the [University of Waterloo](https://uwaterloo.ca/), where I am pursuing my Master's degree in Computer Software Engineering. My passion for software engineering and innovation stems from my strong academic background in electronics engineering, which I obtained from the prestigious [Indian Institute of Technology (IIT) BHU](https://iitbhu.ac.in/) in 2020.

 Before joining University of Waterloo, I contributed significantly to [Samsung's](https://research.samsung.com/sri-n) research and development projects as a Software Engineer for nearly three years. I co-authored three research papers and filed four patents, all aiming to enhance the user experience and push the boundaries of technology. Some of the topics I worked on include optical image stabilization, photography rules, audio equalization, and macrophotography. I also earned multiple certifications in data structures, Python, and deep learning, to further develop my skills and knowledge. My journey is driven by a relentless commitment to innovation and a vision to create a future where technology knows no limits. I am always eager to learn new things, collaborate with others, and take on new challenges. I would love to connect with you and explore how my expertise and passion can add value to your team and your goals. Together, we can shape the future of technology.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pattern Mining of Time Series
        link: Link to project 
        link_text: Link Text
        additional_links:
          - title:  Github page for project 
            icon: fab fa-github
            url: Link to project 
        description: | # this will include new lines to allow paragraphs
          - Developing a novel method to identify distinct and recurring patterns in a given time series. The primary focus of this approach is to ensure high coverage
            of the time series.
          - The solution consists of three stages:
            1. The first stage, Used an established sub-sequences similarity computing method called matrix profile.
            2. The second stage applied constraints on the co-existence of the different candidates and constraints on 
               their selection for the final output.
            3. In the third stage, a constraint solver selected the best-fitting patterns that maximized a gain function 
               while adhering to the given constraints.
      - layout: left
        title: Autonomous Robot Navigation & Object Detection Using Image Processing
        link: ## 
        link_text: ##
        # additional_links:
        #   - title:  Github page for project 
        #     icon: fab fa-github
        #     url: Link to project 
        description:
           - Developed an autonomous robot using MATLAB for color segmentation, enabling detection of objects based on 
             different colors.
           - Implemented Dijkstra's algorithm for pathfinding, ensuring efficient navigation to deliver objects to 
             desired locations while receiving real-time input from a top-mounted camera for continuous monitoring.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: "<img src='images/uw_icon.png' alt='University of Waterloo' width='220' style='display: block; float: left;'/>"
        sub_title: Graduate Research Student
        icon: images/uw_icon.png
        caption: Sep 2023 - Current
        #link: https://uwaterloo.ca/
        description: | # this will include new lines to allow paragraphs
          As a Graduate Research Student at the University of Waterloo, under the guidance of Supervisor Sebastian Fischmeister, 
          I am pursuing a MASc thesis in computer software.

          Scholarship: International Master’s Award of Excellence (IMAE), $12,500

          Award: Graduate research studentship, $41,000

          Courses:
          - Algorithm Design and Analysis
          - Methods and Tools for Software Engineering
          - Data and Knowledge Modeling and Analysis
          - Tools of Intelligent Systems Design

          Teaching Assistant:
          - SE350 Operating System, Winter'24
          - ECE350 RTOS, Spring'24

      - layout: left
        title: Samsung R&D, India
        sub_title: Software Engineer, Camera System
        caption: Feb 2021 - Jul 2023
        #link: https://research.samsung.com/sri-n
        description: | # this will include new lines to allow paragraphs
          - Developed camera sensor firmware update for Android 13 and designed upgrade for the Galaxy-S21 and Flip-3
            phones.
          - Enhanced pro-photography and hyper-lapse modes using Neural Network and Image Segmentation.
          - Developed innovative mobile macro photography enhancement method using multiple lenses and light sources for 
            semantic analysis, correcting blur, shadows, and glare for improved clarity and focus.
          - Developed a method to combat image blurriness by intelligently selecting frames and correcting sensor data, significantly
            reducing blurring and enhancing overall photograph quality for sharper, clearer outcomes.

      - layout: left
        title: Samsung R&D, India
        sub_title: Software Engineer Intern
        caption: May 2019 - Jul 2019
        #link: https://research.samsung.com/sri-n

        description: | # this will include new lines to allow paragraphs
          Image Style Transfer
            - Applied image processing to combine a sequence of photos, extracting the best segments individually to create the
              finest composite image.
            - Developed a model to transfer the style of one image region into another image region associated with
              semantic categories, such as sky, road, and person.
            - Trained our model on MIT ADE20K Dataset which contains more than 20K scene-centric
              images of 150 different object categories.
            - Reduced 150 classes of ADE20K Dataset to 27 classes which were of our interest resulting in
              enhanced segmentation speed.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: "<img src='images/uw_icon.png' alt='University of Waterloo' width='220' style='display: block; float: left;'/>"
        sub_title: Master's (MASc, thesis)
        caption: 2023 - 2025
        description: | # this will include new lines to allow paragraphs
          I am a Graduate Research Student at the [University of Waterloo](https://uwaterloo.ca/), where I am pursuing my Master's degree in Computer Software Engineering. My passion for software engineering and innovation stems from my strong academic background in electronics engineering, which I obtained from the prestigious [Indian Institute of Technology (IIT) BHU](https://iitbhu.ac.in/) in 2020.

      - layout: top-left
        title: "<img src='images/iitbhu.png' alt='IIT BHU' width='220' style='display: block; float: left;'/>"
        #title: "<img src='images/iitbhu1.png' alt='IIT BHU' width='220' style='display: block; margin-left: auto; margin-right: auto;'/>"
        sub_title: Bachelor of Technology in Electronics Engineering
        caption: 2016 - 2020
        description: | # this will include new lines to allow paragraphs
          The Indian Institute of Technology (IIT) BHU is a prestigious institution that played a pivotal role in shaping my academic foundation in electronics engineering. Graduating in 2020, I acquired a comprehensive education that fuels my passion for software engineering and innovation.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Well, I'm someone who finds joy in capturing moments through the lens of a camera. Photography isn't just a hobby for me; it's a passion that ignites my creativity and allows me to express myself in unique ways.

      When I'm behind the camera, I'm not just snapping pictures; I'm telling stories. Whether it's the vibrant colors of a sunset, the candid laughter of friends, or the intricate details of everyday life, I love freezing those fleeting moments in time.

      So, that's a little more about me – a storyteller, an explorer, and a lover of life through the lens of my camera.




# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
